### ISSUE TITLE
mongoclient >= 3.0

### ISSUE THREAD

**Issue by franckFleet** [dycodedev/mongo-datatable#6]
with this version 3.0 of mongoclient (mine), i have to init options with : 
`options.search = {value : ""};`
for not having assert error !

even with this line, using the sample code, i have the foowing result : 
```
{
  "draw": 0,
  "recordsTotal": 0,
  "recordsFiltered": 0,
  "data": [],
  "error": "Columns must be defined!"
}
```

very strange !

**Comment by alwint3r** [comment]
Hi @franckFleet,

Sorry for the late response, I think this module is working fine with mongodb native driver v3. I added the example of using this module with mongodb native driver v3 on the README.

I will close this issue, feel free to re-open if further issue comes up.
